spring:
  application:
    name: cointrail-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cointrail}
    username: ${DB_USERNAME:cointrail}
    password: ${DB_PASSWORD:cointrail}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    com.deepak.cointrailapi: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true

info:
  app:
    name: CoinTrail API
    description: Personal Finance and Expense Tracker API
    version: 1.0.0

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

app:
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:5173}

server:
  port: 8081