INSERT INTO categories (
    name,
    type,
    system,
    active,
    user_id,
    created_at,
    updated_at
)
VALUES
    -- Expense categories
    ('Food', 'EXPENSE', TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Travel', 'EXPENSE', TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Shopping', 'EXPENSE', TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Entertainment', 'EXPENSE', TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Bills', 'EXPENSE', TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Health', 'EXPENSE', TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Education', 'EXPENSE', TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Other', 'EXPENSE', TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    -- Additional V2 expense categories
    ('Rent', 'EXPENSE', TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Subscription', 'EXPENSE', TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    -- Income categories
    ('Salary', 'INCOME', TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Bonus', 'INCOME', TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Freelance', 'INCOME', TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Interest', 'INCOME', TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Other Income', 'INCOME', TRUE, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);